bundler_args: --without development
language: ruby
rvm:
  - 2.2
  - 2.3.3
  - 2.4.0-preview3
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.4.0-preview3
    - rvm: ruby-head
  fast_finish: true
sudo: false
